const dogs=[
{id:'billie',name:'Billie',image:'billie.webp',age:1,sex:'Male',weight:'55 lbs.',breed:'Lab Mix',fixed:'Neutered',microchip:true,heartworm:'HW-',status:'available',traits:['calm'],labels:['Vaccines current','Microchipped','Gentle'],quips:'A smiley boy with a heart full of love and a sweet, gentle spirit.',bio:'Billie is a smiley boy with a heart full of love. He was found roaming alongside Misty, and while we do not know what his past looked like, it is clear that it never dimmed his sweet spirit. Billie is a kind, gentle pup who is ready to trade life on the streets for a loving home where he can finally relax and be someone’s best friend.',featured:1},
{id:'bronco',name:'Bronco',image:'bronco.webp',age:1,sex:'Male',weight:'50 lbs.',breed:'Pit Mix',fixed:'Neutered',microchip:true,heartworm:'HW-',status:'available',traits:['dogs'],labels:['Vaccines current','Microchipped','Dog-friendly'],quips:'Fun-loving, easygoing, and always ready for his next adventure.',bio:'Bronco is a fun-loving, sweet pup who is always ready for his next adventure. He loves walks and gets excited to head outside to play. His happy, easygoing personality shines in the yard, where he has become the unofficial dog greeter for new arrivals because he gets along wonderfully with other dogs at the shelter.',featured:2},
{id:'duke',name:'Duke',image:'duke.webp',age:2,sex:'Male',weight:'70 lbs.',breed:'Husky Mix',fixed:'Neutered',microchip:false,heartworm:'HW+',status:'available',traits:['dogs','treatment'],labels:['Vaccines current','Dog-friendly','Sponsored treatment'],quips:'Sweet, energetic, playful, and ready for an active home.',bio:'Duke is a sweet and energetic Husky mix with a playful spirit and a big heart. He is great with other dogs and would love an active home where he can run, play, and be part of the fun. He is a lively mix of youthful energy and cuddly charm.',featured:6},
{id:'gus',name:'Gus',image:'gus.webp',age:1,sex:'Male',weight:'55 lbs.',breed:'Lab Mix',fixed:'Neutered',microchip:true,heartworm:'HW-',status:'available',traits:['dogs','calm'],labels:['Vaccines current','Microchipped','Dog-friendly'],quips:'Friendly, social, easygoing, and already a lovely leash walker.',bio:'Gus is a friendly, happy pup who loves everyone he meets. He enjoys playing with other dogs, walks beautifully on a leash, and is always excited to settle down with a good bone to chew. With his social personality and easygoing nature, Gus is ready to be a wonderful companion.',featured:7},
{id:'max',name:'Max',image:'max.webp',age:2,sex:'Male',weight:'41 lbs.',breed:'Belgian Malinois',fixed:'Neutered',microchip:true,heartworm:'HW+',status:'available',traits:['dogs','treatment'],labels:['Vaccines current','Dog-friendly','Sponsored treatment'],quips:'A happy, goofy boy who loves attention and staying close to his people.',bio:'Max loves people of all ages and does well with other dogs. He is a happy, goofy boy who loves being close and soaking up attention. If you are looking for a loyal best friend who will keep you smiling, match your energy, and happily be your built-in cuddle buddy, Max would love to meet you.',featured:9},
{id:'misty',name:'Misty',image:'misty.webp',age:2,sex:'Female',weight:'45 lbs.',breed:'Pit Mix',fixed:'Spayed',microchip:true,heartworm:'HW-',status:'available',traits:['dogs'],labels:['Vaccines current','Microchipped','Dog-friendly'],quips:'Resilient, incredibly sweet, and unable to resist chasing hose water.',bio:'Misty has not had an easy life. Found as a stray, she was painfully thin, covered in scars, and had already been forced to have litters. Even so, she is incredibly sweet, loves people, gets along well with other dogs, and cannot resist chasing water from a hose. Now she is ready to leave her past behind and find the loving family she has always deserved.',featured:10},
{id:'roxy',name:'Roxy',image:'roxy.webp',age:1,sex:'Female',weight:'39 lbs.',breed:'Belgian Malinois',fixed:'Spayed',microchip:true,heartworm:'HW-',status:'available',traits:['calm'],labels:['Vaccines current','Microchipped','Leash-trained'],quips:'Gentle and a little shy, with basic commands and polite leash manners.',bio:'Roxy is a gentle, sweet girl who is a little shy with new people but is learning that humans are safe and kind. She melts for reassuring pets and has been nothing but loving as staff get to know her. She knows basic commands and walks politely on leash. Roxy is ready for a calm, patient home where she can continue to blossom.',featured:12},
{id:'snowball',name:'Snowball',image:'snowball.webp',age:2,sex:'Female',weight:'46 lbs.',breed:'Husky Mix',fixed:'Spayed',microchip:true,heartworm:'HW-',status:'pending',traits:['calm'],labels:['Vaccines current','Microchipped','Calm'],quips:'A laid-back girl who enjoys short strolls, cozy naps, and quiet company.',bio:'Snowball is a laid-back girl who knows how to enjoy the simple things in life. She loves short strolls, cozy nap times, and relaxing by your side. If you are looking for a calm companion with a gentle spirit, Snowball may be the perfect match.',featured:13},
{id:'nina',name:'Nina',image:'nina.jpg',age:1,sex:'Female',weight:'25 lbs.',breed:'Alaskan Klee-Kai',fixed:'Spayed',microchip:false,heartworm:'HW-',status:'available',traits:['calm'],labels:['Vaccines current','Microchipped','Calm'],quips:'More info to come!',bio:'More info coming soon.',featured:14},
{id:'chloe',name:'Chloe',image:'chloe.jpg',age:3,sex:'Female',weight:'10 lbs.',breed:'Chihuahua',fixed:'Spayed',microchip:false,heartworm:'HW-',status:'available',traits:['calm'],labels:['Vaccines current','Microchipped','Calm'],quips:'More info to come!',bio:'More info coming soon.',featured:15},
{id:'rosie',name:'Rosie',image:'rosie.webp',age:3,sex:'Female',weight:'44 lbs.',breed:'Labrador Mix',fixed:'Spayed',microchip:false,heartworm:'HW+',status:'available',traits:['treatment'],labels:['Vaccines current','Sponsored treatment','People-friendly'],quips:'A treat-loving sweetheart who enjoys people of all ages.',bio:'Rosie is a sweetheart who is happy to perform for treats. She seems to love people of all ages. Kennel staff are still giving her time before testing her with other dogs, so her dog compatibility should be confirmed before adoption. She is looking for her perfect home.',featured:11}
];
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const grid=q('#dog-grid'),searchInput=q('#search-input'),sortSelect=q('#sort-select'),resultCount=q('#results-count'),clearFilters=q('#clear-filters'),emptyState=q('#empty-state'),dialog=q('#dog-dialog'),dialogContent=q('#dialog-content'),toast=q('#toast');
let activeFilter='all';let favorites;try{favorites=new Set(JSON.parse(localStorage.getItem('gp-dog-favorites')||'[]'))}catch{favorites=new Set()}
q('#featured-count').textContent=dogs.length;
function card(d){return `<article class="dog-card reveal is-visible" data-id="${d.id}"><div class="dog-card-media" data-open-dog="${d.id}" tabindex="0" role="button" aria-label="View ${d.name}'s profile"><img src="images/${d.image}" alt="${d.name}, an adoptable dog" loading="lazy"><span class="availability-chip ${d.status==='pending'?'pending':''}"><span class="status-dot"></span>${d.status==='pending'?'Adoption pending':'Available'}</span><button class="favorite-button ${favorites.has(d.id)?'is-favorite':''}" type="button" data-favorite="${d.id}" aria-label="${favorites.has(d.id)?'Remove':'Save'} ${d.name} ${favorites.has(d.id)?'from':'to'} favorites">${favorites.has(d.id)?'♥':'♡'}</button></div><div class="dog-card-body"><div class="dog-card-title"><div><h3>${d.name}</h3><div class="dog-meta">${d.age} ${d.age===1?'year':'years'} · ${d.sex} · ${d.breed}</div></div><button class="profile-arrow" data-open-dog="${d.id}" type="button" aria-label="Open ${d.name}'s profile">↗</button></div><div class="tag-row">${d.labels.slice(0,3).map(x=>`<span class="tag">${x}</span>`).join('')}</div><p class="dog-quips">${d.quips}</p></div></article>`}
function filtered(){const term=searchInput.value.trim().toLowerCase();let list=dogs.filter(d=>(!term||d.name.toLowerCase().includes(term))&&(activeFilter==='all'||d.traits.includes(activeFilter)));if(sortSelect.value==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(sortSelect.value==='age')list.sort((a,b)=>a.age-b.age||a.name.localeCompare(b.name));if(sortSelect.value==='featured')list.sort((a,b)=>a.featured-b.featured);return list}
function render(){const list=filtered();grid.innerHTML=list.map(card).join('');resultCount.textContent=`${list.length} ${list.length===1?'dog':'dogs'}`;emptyState.hidden=!!list.length;clearFilters.hidden=activeFilter==='all'&&!searchInput.value}
function showToast(m){toast.textContent=m;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2200)}
function saveFavorites(){localStorage.setItem('gp-dog-favorites',JSON.stringify([...favorites]))}
function toggleFavorite(id){const d=dogs.find(x=>x.id===id);favorites.has(id)?favorites.delete(id):favorites.add(id);saveFavorites();render();showToast(favorites.has(id)?`${d.name} saved to favorites`:`${d.name} removed from favorites`)}
function healthNote(d){return d.heartworm==='HW+'?'Heartworm positive. Ask kennel staff about the sponsored treatment available for this dog.':'Heartworm negative. Listed as up to date on vaccines and on heartworm/flea preventative.'}
function openDog(id){const d=dogs.find(x=>x.id===id);if(!d)return;dialogContent.innerHTML=`<div class="dialog-grid"><div class="dialog-media"><img src="images/${d.image}" alt="${d.name}, an adoptable dog"></div><div class="dialog-info"><span class="dialog-kicker">${d.status==='pending'?'Adoption pending':'Available for adoption'}</span><h2>${d.name}</h2><div class="dialog-meta">${d.age} ${d.age===1?'year':'years'} · ${d.sex} · ${d.breed}</div><div class="tag-row">${d.labels.map(x=>`<span class="tag">${x}</span>`).join('')}</div><p class="dialog-bio">${d.bio}</p><div class="health-panel"><span>Health</span><strong>${d.heartworm} · ${d.fixed} · Vaccines current${d.microchip?' · Microchipped':''}</strong><p>${healthNote(d)}</p></div><div class="facts-grid"><div class="fact"><span>Status</span><strong>${d.status==='pending'?'Pending':'Available'}</strong></div><div class="fact"><span>Age</span><strong>${d.age} ${d.age===1?'year':'years'}</strong></div><div class="fact"><span>Weight</span><strong>${d.weight}</strong></div><div class="fact"><span>Sex</span><strong>${d.sex}</strong></div></div><div class="dialog-actions"><a class="button button-primary" href="#contact" data-inquire-dog="${d.name}">Ask about ${d.name}</a><button class="button share-button" data-share-dog="${d.id}" type="button">Share profile</button></div></div></div>`;dialog.showModal();document.body.classList.add('modal-open')}
function closeDialog(){if(dialog.open)dialog.close();document.body.classList.remove('modal-open')}
async function shareDog(id){const d=dogs.find(x=>x.id===id),url=`${location.href.split('#')[0]}#${d.id}`,data={title:`Meet ${d.name} | Galena Park Kennel`,text:`Meet ${d.name}, an adoptable dog at the City of Galena Park Kennel.`,url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(url);showToast('Profile link copied')}}catch{}}
async function shareSite(){try{if(navigator.share)await navigator.share({title:document.title,text:'Meet adoptable dogs at the City of Galena Park Kennel.',url:location.href});else{await navigator.clipboard.writeText(location.href);showToast('Website link copied')}}catch{}}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open-dog]');if(open)openDog(open.dataset.openDog);const fav=e.target.closest('[data-favorite]');if(fav){e.stopPropagation();toggleFavorite(fav.dataset.favorite)}const share=e.target.closest('[data-share-dog]');if(share)shareDog(share.dataset.shareDog);if(e.target.closest('[data-share-site]'))shareSite();const inquiry=e.target.closest('[data-inquire-dog]');if(inquiry){const sel=q('#contact-dog');if(sel)sel.value=inquiry.dataset.inquireDog;closeDialog();setTimeout(()=>q('#contact')?.scrollIntoView({behavior:'smooth'}),50)}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-open-dog][role="button"]')){e.preventDefault();openDog(e.target.dataset.openDog)}});q('.dialog-close').addEventListener('click',closeDialog);dialog.addEventListener('click',e=>{if(e.target===dialog)closeDialog()});searchInput.addEventListener('input',render);sortSelect.addEventListener('change',render);qa('.filter-pill').forEach(btn=>btn.addEventListener('click',()=>{qa('.filter-pill').forEach(x=>x.classList.remove('is-active'));btn.classList.add('is-active');activeFilter=btn.dataset.filter;render()}));clearFilters.addEventListener('click',()=>{activeFilter='all';searchInput.value='';qa('.filter-pill').forEach(x=>x.classList.toggle('is-active',x.dataset.filter==='all'));render()});const menu=q('.menu-button'),nav=q('.site-nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('is-open',!open)});nav.addEventListener('click',()=>{nav.classList.remove('is-open');menu.setAttribute('aria-expanded','false')});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.1});qa('.reveal').forEach(el=>observer.observe(el));q('#year').textContent=new Date().getFullYear();render();if(location.hash){const id=location.hash.slice(1);if(dogs.some(d=>d.id===id))setTimeout(()=>openDog(id),300)}
